# Generated by Django 6.0.3 on 2026-03-30 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='apointment_code',
            new_name='appointment_code',
        ),
    ]
